[package]
name = "cetz"
version = "0.0.1"
repository = "https://github.com/johannes-wolf/typst-canvas"
entrypoint = "lib.typ"
authors = [
  "Johannes Wolf <https://github.com/johannes-wolf>",
  "fenjalien <https://github.com/fenjalien>"
]
license = "Apache-2.0"
description = "Drawing with Typst made easy, providing an API inspired by TikZ and Processing."
exclude = [ "*.png", "manual.pdf", "manual.typ" ]
