[package]
name = "cetz"
version = "0.0.2"
repository = "https://github.com/johannes-wolf/typst-canvas"
entrypoint = "src/lib.typ"
authors = [
  "Johannes Wolf <https://github.com/johannes-wolf>",
  "fenjalien <https://github.com/fenjalien>"
]
license = "Apache-2.0"
description = "Drawing with Typst made easy, providing an API inspired by TikZ and Processing. Includes modules for plotting, charts and tree layout."
exclude = [ "/gallery/*", "manual.pdf", "manual.typ" ]
